---
title: "Something"
author: "Mauro Camara Escudero"
date: "2/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# IMPORTS

```{r}
library(readr)
library(ggplot2)
library(viridis)
library(Rcpp)
library(RcppArmadillo)
library(gridExtra)
library(microbenchmark)
library(mvtnorm)
```

# READING DATA AND QUESTION 2 IN R
```{r}
set.seed(123)
solarAU <- read_csv(
  file="solarAU.csv", 
  col_types = cols(
    X1=col_integer(),
    prod=col_double(),
    toy=col_double(),
    tod=col_double()
  ))
# Work with log production, since it's less skewed
solarAU$logprod <- log(solarAU$prod+0.01)  # +0.01 to avoid -Inf when production is 0

X <- with(solarAU, cbind(1, tod, tod^2, toy, toy^2))
y <- solarAU$logprod
colnames(X) <- c("intercept", "tod", "todsq", "toy", "toysq")

lmLocal <- function(y, x0, X0, x, X, H){
  w <- dmvnorm(x, x0, H)
  fit <- lm(y ~ -1 + X, weights = w)
  return( t(X0) %*% coef(fit) )
}
set.seed(123)
n <- nrow(X)
nsub <- 2e3
sub <- sample(1:n, nsub, replace = FALSE)

y <- solarAU$logprod
solarAU_sub <- solarAU[sub, ]
x <- as.matrix(solarAU[c("tod", "toy")])
x0 <- x[sub, ]
X0 <- X[sub, ]
predLocal <- sapply(1:nsub, function(ii){
  lmLocal(y = y, x0 = x0[ii, ], X0 = X0[ii, ], x = x, X = X, H = diag(c(1, 0.1)^2))
})
```


# SOURCE CPP CODE
```{r}
sourceCpp("newcpp.cpp")
```

```{r}
H <- diag(c(1, 0.1)^2)
```

# LOOK AT THE RESULT FROM THE R VERSION
```{r}
matrix(predLocal[1:10])
```


# CPP CODE FOR STUFF


```{r}
system.time(local_Rcpp(y, x0, X0, x, X, H))
```



```{r}
system.time(sapply(1:nsub, function(ii){
  lmLocal(y = y, x0 = x0[ii, ], X0 = X0[ii, ], x = x, X = X, H = diag(c(1, 0.1)^2))
}))
```





